name: Go CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"

      - name: Download dependencies
        run: go mod download

      - name: Run golangci-lint (excluding 'unused')
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --disable=unused

  test:
    name: Run go test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v -race -cover
